site_name: TechWriter Summary
site_url: https://daymonri.github.io/tws/
site_description: Website with a basic theory for an Middle+ Technical writer.
site_author: Alexey Frolov
repo_url: https://github.com/daymonri/tws.git

theme: material

nav:
  - TechDoc:
    - Определение технической документации: TechDoc1.md
    - Техническая документация – процесс и артефакт: TechDoc2.md
    - Жизненный цикл технического документа: TechDoc3.md
    - Документационный инструментарий: TechDoc4.md

copyright: Copyright &copy; 2024 Alexey Frolov