site_name: TechWriter Summary
site_url: https://daymonri.github.io/tws/
site_description: Website with a basic theory for an Middle+ Technical writer.
site_author: Alexey Frolov
repo_url: https://github.com/daymonri/tws.git

theme: material

nav:
  - TechDoc:
    - Определение технической документации: TechDoc1.md
    - Техническая документация – процесс и артефакт: TechDoc2.md
    - Жизненный цикл технического документа: TechDoc3.md
    - Документационный инструментарий: TechDoc4.md
  - Standarts/Notations:
    - Стандарт DITA: StandartsNotations1.md
    - Нотация C4: StandartsNotations2.md
    - Нотация BPMN: StandartsNotations3.md
    - Нотация UML (SD): StandartsNotations4.md

copyright: Copyright &copy; 2024 Alexey Frolov

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - javascripts/highlight.js
extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/styles/default.min.css

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false